using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Aetheria.WaitTimeSimulator;

public static class SimulatorTelemetry
{
    public const string ActivitySourceName = "Aetheria.WaitTimeSimulator";

    public const string MeterName = "Aetheria.WaitTimeSimulator";

    public static readonly ActivitySource ActivitySource = new(ActivitySourceName);

    public static readonly Meter Meter = new(MeterName);

    public static readonly Counter<long> SimulationTicks = Meter.CreateCounter<long>("park.simulation.ticks", description: "Number of simulated park-time intervals.");

    public static readonly Counter<long> WaitTimeChanges = Meter.CreateCounter<long>("park.simulation.wait_time_changes", description: "Number of simulated attraction wait-time changes.");

    public static readonly Histogram<int> SimulatedWaitTime = Meter.CreateHistogram<int>("park.simulation.wait_time", unit: "min", description: "Wait times generated by the park simulator.");
}